production:
  maintenance_reminders:
    class: MaintenanceRemindersJob
    schedule: at 1am every day
  complete_past_bookings:
    class: CompletePastBookingsJob
    schedule: at 1am every day

development:
  maintenance_reminders:
    class: MaintenanceRemindersJob
    schedule: at 1am every day
  complete_past_bookings:
    class: CompletePastBookingsJob
    schedule: at 1am every day

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
